name: Build release
on:
  release:
    types:
      - created
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./build-clang.cmd
    - uses: thucfb-lib-mirror/upload-to-release@1.0.0
      with:
        name: shim.zip
        path: bin/shim.zip
        repo-token: ${{ secrets.GITHUB_TOKEN }}
